# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34e9507950d1aaa0f3b806b3b315c295d605d2dd91c17d617b2d3f71213fa231b73a9113fde0c60e92bb045dc6c39484a7bd3dbdb210c35bc231b7acf84e16f2

test:
  secret_key_base: f96a939321b3bf47a036ba633cd3048ea6f0d667f01ced1d84cc62453cbe4af235787e5e1fc47cb0202477a27806e19d759d62f4ee2bce7768454fb1dd0f3459

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
